CREATE TABLE Users (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Orders (
    Id INT IDENTITY PRIMARY KEY,
    UserId INT,
    Total DECIMAL(10,2),
    CreatedAt DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

ALTER TABLE Users ADD Phone NVARCHAR(20);